apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobportal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobportal
  template:
    metadata:
      labels:
        app: jobportal
    spec:
      containers:
      - name: jobportal
        image: icr.io/ibm-project/jobportal:v1
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector:
    app: jobportal
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer